export const movieSeats = [
    // Row A
    [
      { id: 1, number: "A1", status: "available" },
      { id: 2, number: "A2", status: "available" },
      { id: 3, number: "A3", status: "available" },
      { id: 4, number: "A4", status: "booked" },
      { id: 5, number: "A5", status: "booked" },
      { id: 6, number: "A6", status: "available" },
      { id: 7, number: "A7", status: "available" },
      { id: 8, number: "A8", status: "available" },
      { id: 9, number: "A9", status: "available" },
      { id: 10, number: "A10", status: "available" },
    ],
    // Row B
    [
      { id: 11, number: "B1", status: "available" },
      { id: 12, number: "B2", status: "available" },
      { id: 13, number: "B3", status: "available" },
      { id: 14, number: "B4", status: "booked" },
      { id: 15, number: "B5", status: "available" },
      { id: 16, number: "B6", status: "available" },
      { id: 17, number: "B7", status: "available" },
      { id: 18, number: "B8", status: "available" },
      { id: 19, number: "B9", status: "available" },
      { id: 20, number: "B10", status: "available" },
    ],
    // Row C
    [
      { id: 21, number: "C1", status: "available" },
      { id: 22, number: "C2", status: "available" },
      { id: 23, number: "C3", status: "available" },
      { id: 24, number: "C4", status: "available" },
      { id: 25, number: "C5", status: "booked" },
      { id: 26, number: "C6", status: "available" },
      { id: 27, number: "C7", status: "available" },
      { id: 28, number: "C8", status: "available" },
      { id: 29, number: "C9", status: "available" },
      { id: 30, number: "C10", status: "available" },
    ],
    // Row D
    [
      { id: 31, number: "D1", status: "available" },
      { id: 32, number: "D2", status: "available" },
      { id: 33, number: "D3", status: "available" },
      { id: 34, number: "D4", status: "available" },
      { id: 35, number: "D5", status: "available" },
      { id: 36, number: "D6", status: "available" },
      { id: 37, number: "D7", status: "available" },
      { id: 38, number: "D8", status: "available" },
      { id: 39, number: "D9", status: "booked" },
      { id: 40, number: "D10", status: "available" },
    ],
    // Row E
    [
      { id: 41, number: "E1", status: "available" },
      { id: 42, number: "E2", status: "available" },
      { id: 43, number: "E3", status: "available" },
      { id: 44, number: "E4", status: "booked" },
      { id: 45, number: "E5", status: "available" },
      { id: 46, number: "E6", status: "available" },
      { id: 47, number: "E7", status: "available" },
      { id: 48, number: "E8", status: "available" },
      { id: 49, number: "E9", status: "booked" },
      { id: 50, number: "E10", status: "available" },
    ],
    //Row F
    [
      { id: 51, number: "F1", status: "available" },
      { id: 52, number: "F2", status: "available" },
      { id: 53, number: "F3", status: "available" },
      { id: 54, number: "F4", status: "available" },
      { id: 55, number: "F5", status: "available" },
      { id: 56, number: "F6", status: "available" },
      { id: 57, number: "F7", status: "available" },
      { id: 58, number: "F8", status: "available" },
      { id: 59, number: "F9", status: "available" },
      { id: 60, number: "F10", status: "available" },
    ],
    [
      { id: 61, number: "G1", status: "available" },
      { id: 62, number: "G2", status: "available" },
      { id: 63, number: "G3", status: "available" },
      { id: 64, number: "G4", status: "available" },
      { id: 65, number: "G5", status: "booked" },
      { id: 66, number: "G6", status: "available" },
      { id: 67, number: "G7", status: "available" },
      { id: 68, number: "G8", status: "available" },
      { id: 69, number: "G9", status: "available" },
      { id: 70, number: "G10", status: "available" },
    ],
    [
      { id: 71, number: "H1", status: "available" },
      { id: 72, number: "H2", status: "available" },
      { id: 73, number: "H3", status: "available" },
      { id: 74, number: "H4", status: "available" },
      { id: 75, number: "H5", status: "available" },
      { id: 76, number: "H6", status: "available" },
      { id: 77, number: "H7", status: "available" },
      { id: 78, number: "H8", status: "available" },
      { id: 79, number: "H9", status: "available" },
      { id: 80, number: "H10", status: "available" },
    ],
    [
      { id: 81, number: "I1", status: "available" },
      { id: 82, number: "I2", status: "available" },
      { id: 83, number: "I3", status: "available" },
      { id: 84, number: "I4", status: "available" },
      { id: 85, number: "I5", status: "available" },
      { id: 86, number: "I6", status: "available" },
      { id: 87, number: "I7", status: "available" },
      { id: 88, number: "I8", status: "available" },
      { id: 89, number: "I9", status: "available" },
      { id: 90, number: "I10", status: "available" },
    ],
    [
      { id: 91, number: "J1", status: "available" },
      { id: 92, number: "J2", status: "available" },
      { id: 93, number: "J3", status: "available" },
      { id: 94, number: "J4", status: "available" },
      { id: 95, number: "J5", status: "available" },
      { id: 96, number: "J6", status: "available" },
      { id: 97, number: "J7", status: "available" },
      { id: 98, number: "J8", status: "available" },
      { id: 99, number: "J9", status: "available" },
      { id: 100, number: "J10", status: "available" },
    ],
  ];